### ISSUE TITLE
Use fwupdate asuswrt-merlin website

### ISSUE THREAD

**Issue by alfredocdmiranda** [henriksommerfeld/asuswrt-merlin-update-check#2]
I was looking inside the code and find this URL https://fwupdate.asuswrt-merlin.net/manifest.txt that is used to check for updates in the firmware. Would it be easier to use this instead of parse the page?

**Comment by henriksommerfeld** [comment]
Oh, I completely missed this, saw it now. Indeed looks simpler, thanks!

**Comment by henriksommerfeld** [comment]
Fixed in latest commits.
